backend test scripts, but refCompile not working yet

diff --git a/tests/backend_test b/tests/backend_test
--- a/tests/backend_test
+++ b/tests/backend_test
@@ -1,2 +1,211 @@
 #!/bin/bash
-echo "Backend Tests should run here, WIP"
+
+javac BackendTest.java
+
+failed=0
+total=0
+
+runBackendTest(){
+    java BackendTest "$1"
+    code=$?
+    ((total=total+1))
+    if [ $code -ne 0 ]; then
+        (( failed = failed + 1 ))
+        echo "Error: Compiler returned $code instead of 0 for $1"
+    fi
+}
+
+
+echo "=============== Running Backend Tests ==============="
+echo "..."
+runBackendTest examples/valid/advanced/binarySortTree.wacc
+runBackendTest examples/valid/advanced/ticTacToe.wacc
+runBackendTest examples/valid/advanced/hashTable.wacc
+runBackendTest examples/valid/array/arrayLength.wacc
+runBackendTest examples/valid/array/arrayEmpty.wacc
+runBackendTest examples/valid/array/array.wacc
+runBackendTest examples/valid/array/arrayLookup.wacc
+runBackendTest examples/valid/array/modifyString.wacc
+runBackendTest examples/valid/array/printRef.wacc
+runBackendTest examples/valid/array/arraySimple.wacc
+runBackendTest examples/valid/array/arrayNested.wacc
+runBackendTest examples/valid/array/arrayPrint.wacc
+runBackendTest examples/valid/array/arrayBasic.wacc
+runBackendTest examples/valid/pairs/printNull.wacc
+runBackendTest examples/valid/pairs/printNullPair.wacc
+runBackendTest examples/valid/pairs/printPair.wacc
+runBackendTest examples/valid/pairs/nestedPair.wacc
+runBackendTest examples/valid/pairs/createRefPair.wacc
+runBackendTest examples/valid/pairs/free.wacc
+runBackendTest examples/valid/pairs/writeSnd.wacc
+runBackendTest examples/valid/pairs/writeFst.wacc
+runBackendTest examples/valid/pairs/printPairOfNulls.wacc
+runBackendTest examples/valid/pairs/null.wacc
+runBackendTest examples/valid/pairs/createPair02.wacc
+runBackendTest examples/valid/pairs/createPair.wacc
+runBackendTest examples/valid/pairs/checkRefPair.wacc
+runBackendTest examples/valid/pairs/createPair03.wacc
+runBackendTest examples/valid/pairs/readPair.wacc
+runBackendTest examples/valid/pairs/linkedList.wacc
+runBackendTest examples/valid/if/if1.wacc
+runBackendTest examples/valid/if/whitespace.wacc
+runBackendTest examples/valid/if/ifFalse.wacc
+runBackendTest examples/valid/if/ifBasic.wacc
+runBackendTest examples/valid/if/if6.wacc
+runBackendTest examples/valid/if/ifTrue.wacc
+runBackendTest examples/valid/if/if5.wacc
+runBackendTest examples/valid/if/if4.wacc
+runBackendTest examples/valid/if/if3.wacc
+runBackendTest examples/valid/if/if2.wacc
+runBackendTest examples/valid/runtimeErr/integerOverflow/intJustOverflow.wacc
+runBackendTest examples/valid/runtimeErr/integerOverflow/intnegateOverflow.wacc
+runBackendTest examples/valid/runtimeErr/integerOverflow/intmultOverflow.wacc
+runBackendTest examples/valid/runtimeErr/integerOverflow/intnegateOverflow3.wacc
+runBackendTest examples/valid/runtimeErr/integerOverflow/intWayOverflow.wacc
+runBackendTest examples/valid/runtimeErr/integerOverflow/intnegateOverflow2.wacc
+runBackendTest examples/valid/runtimeErr/integerOverflow/intUnderflow.wacc
+runBackendTest examples/valid/runtimeErr/integerOverflow/intnegateOverflow4.wacc
+runBackendTest examples/valid/runtimeErr/nullDereference/readNull2.wacc
+runBackendTest examples/valid/runtimeErr/nullDereference/useNull2.wacc
+runBackendTest examples/valid/runtimeErr/nullDereference/setNull1.wacc
+runBackendTest examples/valid/runtimeErr/nullDereference/freeNull.wacc
+runBackendTest examples/valid/runtimeErr/nullDereference/setNull2.wacc
+runBackendTest examples/valid/runtimeErr/nullDereference/useNull1.wacc
+runBackendTest examples/valid/runtimeErr/nullDereference/readNull1.wacc
+runBackendTest examples/valid/runtimeErr/doubleFrees/doubleFree.wacc
+runBackendTest examples/valid/runtimeErr/doubleFrees/hiddenDoubleFree.wacc
+runBackendTest examples/valid/runtimeErr/divideByZero/divZero.wacc
+runBackendTest examples/valid/runtimeErr/divideByZero/divideByZero.wacc
+runBackendTest examples/valid/runtimeErr/divideByZero/modByZero.wacc
+runBackendTest examples/valid/runtimeErr/arrayOutOfBounds/arrayOutOfBoundsWrite.wacc
+runBackendTest examples/valid/runtimeErr/arrayOutOfBounds/arrayNegBounds.wacc
+runBackendTest examples/valid/runtimeErr/arrayOutOfBounds/arrayOutOfBounds.wacc
+runBackendTest examples/valid/IO/IOLoop.wacc
+runBackendTest examples/valid/IO/read/echoPuncChar.wacc
+runBackendTest examples/valid/IO/read/echoBigInt.wacc
+runBackendTest examples/valid/IO/read/echoInt.wacc
+runBackendTest examples/valid/IO/read/echoNegInt.wacc
+runBackendTest examples/valid/IO/read/echoChar.wacc
+runBackendTest examples/valid/IO/read/echoBigNegInt.wacc
+runBackendTest examples/valid/IO/read/read.wacc
+runBackendTest examples/valid/IO/IOSequence.wacc
+runBackendTest examples/valid/IO/print/println.wacc
+runBackendTest examples/valid/IO/print/stringAssignmentWithPrint.wacc
+runBackendTest examples/valid/IO/print/printEscChar.wacc
+runBackendTest examples/valid/IO/print/multipleStringsAssignment.wacc
+runBackendTest examples/valid/IO/print/print.wacc
+runBackendTest examples/valid/IO/print/hashInProgram.wacc
+runBackendTest examples/valid/IO/print/printBool.wacc
+runBackendTest examples/valid/IO/print/printInt.wacc
+runBackendTest examples/valid/IO/print/printChar.wacc
+runBackendTest examples/valid/basic/skip/skip.wacc
+runBackendTest examples/valid/basic/skip/comment.wacc
+runBackendTest examples/valid/basic/skip/commentInLine.wacc
+runBackendTest examples/valid/basic/exit/exit-1.wacc
+runBackendTest examples/valid/basic/exit/exitBasic.wacc
+runBackendTest examples/valid/basic/exit/exitBasic2.wacc
+runBackendTest examples/valid/basic/exit/exitWrap.wacc
+runBackendTest examples/valid/scope/printAllTypes.wacc
+runBackendTest examples/valid/scope/scopeSimpleRedefine.wacc
+runBackendTest examples/valid/scope/scopeRedefine.wacc
+runBackendTest examples/valid/scope/indentationNotImportant.wacc
+runBackendTest examples/valid/scope/scope.wacc
+runBackendTest examples/valid/scope/scopeBasic.wacc
+runBackendTest examples/valid/scope/ifNested2.wacc
+runBackendTest examples/valid/scope/ifNested1.wacc
+runBackendTest examples/valid/scope/scopeVars.wacc
+runBackendTest examples/valid/scope/intsAndKeywords.wacc
+runBackendTest examples/valid/function/nested_functions/fixedPointRealArithmetic.wacc
+runBackendTest examples/valid/function/nested_functions/printTriangle.wacc
+runBackendTest examples/valid/function/nested_functions/printInputTriangle.wacc
+runBackendTest examples/valid/function/nested_functions/mutualRecursion.wacc
+runBackendTest examples/valid/function/nested_functions/fibonacciFullRec.wacc
+runBackendTest examples/valid/function/nested_functions/functionConditionalReturn.wacc
+runBackendTest examples/valid/function/nested_functions/simpleRecursion.wacc
+runBackendTest examples/valid/function/nested_functions/fibonacciRecursive.wacc
+runBackendTest examples/valid/function/simple_functions/functionDeclaration.wacc
+runBackendTest examples/valid/function/simple_functions/sameArgName2.wacc
+runBackendTest examples/valid/function/simple_functions/functionManyArguments.wacc
+runBackendTest examples/valid/function/simple_functions/asciiTable.wacc
+runBackendTest examples/valid/function/simple_functions/functionSimple.wacc
+runBackendTest examples/valid/function/simple_functions/incFunction.wacc
+runBackendTest examples/valid/function/simple_functions/sameArgName.wacc
+runBackendTest examples/valid/function/simple_functions/negFunction.wacc
+runBackendTest examples/valid/function/simple_functions/functionUpdateParameter.wacc
+runBackendTest examples/valid/function/simple_functions/functionReturnPair.wacc
+runBackendTest examples/valid/variables/capCharDeclaration.wacc
+runBackendTest examples/valid/variables/negIntDeclaration.wacc
+runBackendTest examples/valid/variables/charDeclaration.wacc
+runBackendTest examples/valid/variables/emptyStringDeclaration.wacc
+runBackendTest examples/valid/variables/stringDeclaration.wacc
+runBackendTest examples/valid/variables/longVarNames.wacc
+runBackendTest examples/valid/variables/boolDeclaration.wacc
+runBackendTest examples/valid/variables/_VarNames.wacc
+runBackendTest examples/valid/variables/charDeclaration2.wacc
+runBackendTest examples/valid/variables/manyVariables.wacc
+runBackendTest examples/valid/variables/intDeclaration.wacc
+runBackendTest examples/valid/variables/boolDeclaration2.wacc
+runBackendTest examples/valid/variables/zeroIntDeclaration.wacc
+runBackendTest examples/valid/variables/puncCharDeclaration.wacc
+runBackendTest examples/valid/expressions/intCalc.wacc
+runBackendTest examples/valid/expressions/multNoWhitespaceExpr.wacc
+runBackendTest examples/valid/expressions/andExpr.wacc
+runBackendTest examples/valid/expressions/divExpr.wacc
+runBackendTest examples/valid/expressions/negBothMod.wacc
+runBackendTest examples/valid/expressions/longSplitExpr.wacc
+runBackendTest examples/valid/expressions/negDivisorDiv.wacc
+runBackendTest examples/valid/expressions/ordAndchrExpr.wacc
+runBackendTest examples/valid/expressions/lessExpr.wacc
+runBackendTest examples/valid/expressions/lessCharExpr.wacc
+runBackendTest examples/valid/expressions/negDividendDiv.wacc
+runBackendTest examples/valid/expressions/longExpr2.wacc
+runBackendTest examples/valid/expressions/longSplitExpr2.wacc
+runBackendTest examples/valid/expressions/minusExpr.wacc
+runBackendTest examples/valid/expressions/intExpr1.wacc
+runBackendTest examples/valid/expressions/greaterEqExpr.wacc
+runBackendTest examples/valid/expressions/plusPlusExpr.wacc
+runBackendTest examples/valid/expressions/lessEqExpr.wacc
+runBackendTest examples/valid/expressions/multExpr.wacc
+runBackendTest examples/valid/expressions/longExpr3.wacc
+runBackendTest examples/valid/expressions/plusNoWhitespaceExpr.wacc
+runBackendTest examples/valid/expressions/plusMinusExpr.wacc
+runBackendTest examples/valid/expressions/negDividendMod.wacc
+runBackendTest examples/valid/expressions/longExpr.wacc
+runBackendTest examples/valid/expressions/boolExpr1.wacc
+runBackendTest examples/valid/expressions/equalsExpr.wacc
+runBackendTest examples/valid/expressions/negDivisorMod.wacc
+runBackendTest examples/valid/expressions/negBothDiv.wacc
+runBackendTest examples/valid/expressions/orExpr.wacc
+runBackendTest examples/valid/expressions/sequentialCount.wacc
+runBackendTest examples/valid/expressions/notequalsExpr.wacc
+runBackendTest examples/valid/expressions/negExpr.wacc
+runBackendTest examples/valid/expressions/stringEqualsExpr.wacc
+runBackendTest examples/valid/expressions/notExpr.wacc
+runBackendTest examples/valid/expressions/greaterExpr.wacc
+runBackendTest examples/valid/expressions/plusExpr.wacc
+runBackendTest examples/valid/expressions/charComparisonExpr.wacc
+runBackendTest examples/valid/expressions/modExpr.wacc
+runBackendTest examples/valid/expressions/minusPlusExpr.wacc
+runBackendTest examples/valid/expressions/minusMinusExpr.wacc
+runBackendTest examples/valid/expressions/boolCalc.wacc
+runBackendTest examples/valid/expressions/minusNoWhitespaceExpr.wacc
+runBackendTest examples/valid/sequence/stringAssignment.wacc
+runBackendTest examples/valid/sequence/charAssignment.wacc
+runBackendTest examples/valid/sequence/intLeadingZeros.wacc
+runBackendTest examples/valid/sequence/boolAssignment.wacc
+runBackendTest examples/valid/sequence/intAssignment.wacc
+runBackendTest examples/valid/sequence/basicSeq.wacc
+runBackendTest examples/valid/sequence/basicSeq2.wacc
+runBackendTest examples/valid/sequence/exitSimple.wacc
+runBackendTest examples/valid/while/whileBasic.wacc
+runBackendTest examples/valid/while/loopIntCondition.wacc
+runBackendTest examples/valid/while/rmStyleAddIO.wacc
+runBackendTest examples/valid/while/whileFalse.wacc
+runBackendTest examples/valid/while/fibonacciFullIt.wacc
+runBackendTest examples/valid/while/whileCount.wacc
+runBackendTest examples/valid/while/min.wacc
+runBackendTest examples/valid/while/max.wacc
+runBackendTest examples/valid/while/whileBoolFlip.wacc
+runBackendTest examples/valid/while/fibonacciIterative.wacc
+runBackendTest examples/valid/while/loopCharCondition.wacc
+runBackendTest examples/valid/while/rmStyleAdd.wacc
